version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/projects/@crucible-common/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
    reviewers:
      - "cmu-sei/crucible-reviewers"
